### PR TITLE
Fix "attempt to compare number with function"

### LINKED ISSUE #2: [Bug] attempt to compare number with function
## Describe the bug
When I run `:Cheatsheet` I'm getting the following error:
```lua
Error detected while processing function <SNR>31_Cheatsheet:
line    5:
E5108: Error executing lua ...zy/opt/cheatsheet.nvim/lua/cheatsheet/telescope/init.lua:47: attempt to compare number with function
stack traceback:
        ...zy/opt/cheatsheet.nvim/lua/cheatsheet/telescope/init.lua:47: in function 'entry_maker'
        ...scope.nvim/lua/telescope/finders/async_static_finder.lua:17: in function 'new_table'
        ...zy/opt/cheatsheet.nvim/lua/cheatsheet/telescope/init.lua:26: in function 'pick_cheat'
        ...te/pack/lazy/opt/cheatsheet.nvim/lua/cheatsheet/init.lua:265: in function 'show_cheatsheet_telescope'
        ...te/pack/lazy/opt/cheatsheet.nvim/lua/cheatsheet/init.lua:272: in function 'show_cheatsheet'
        [string ":lua"]:1: in main chunk
```

## To Reproduce
Run `:Cheatsheet`

## Expected behavior
There shouldn't be any error and the "Cheat" Menu should just open.

## Additional context
I have not tested this with a clean nvim install. I'm using a pretty customized Lunarvim config. I'm pretty sure that they don't do anything out of the ordinary because other windows work just fine. But then again, I don't really know if any of the built-in Telescope windows use those values, but I would assume so. I'm pretty sure that all the values that could be assigned to the width are nil. I tried `width = width()` and that just returned nil.

### PR DESCRIPTION
**Pull request by ZerGo0**
Fixes #2

### CODE REVIEW

File: lua/cheatsheet/telescope/init.lua [hunk 1]
```diff
@@ -38,14 +38,19 @@ M.pick_cheat = function(telescope_opts, opts)
...
+                        width = config.layout_config.width
+                    elseif config.layout_config and config.layout_config[config.layout_strategy] and config.layout_config[config.layout_strategy].width and type(config.layout_config[config.layout_strategy].width) == 'number' then
+                        width = config.layout_config[config.layout_strategy].width
+                    end
+
                     local tel_win_width
                     -- width = 80 -> column width, width = 0.7 -> ratio
                     if width > 1 then
-                        tel_win_width = width
+                        tel_win_width = math.floor(width * 0.6)
```
Comment (ZerGo0) [inline lua/cheatsheet/telescope/init.lua:53]: I'm pretty sure that this should only be the case when the width is `vim.o.columns`. Just using the value results in the window only showing the description, but not the cheatcode. This fixes that
